import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import NavbarPage from "../components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { ProvidersAntdRegistry } from "./AntdRegistry";
import StoreProvider from "./StoreProvider";
import { AuthProvider } from "@/authService/authContext";
import { loadStripe } from "@stripe/stripe-js";
import StripeElement from "./StipeElement";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const stripePromise = loadStripe(
  "pk_test_51M6YTaIOaRhLiCR9IUacPMWr7kIOpNT2oEv4gm3lLOoRyLZ0sQplaW3fiYroKVA63hTjrAq5homSPjhn01lr0z36007McI12l5"
);
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StripeElement>
          <AuthProvider>
            <StoreProvider>
              <ProvidersAntdRegistry>
                <Providers>
                  <NavbarPage></NavbarPage>
                  {children}
                  <Footer />
                </Providers>
              </ProvidersAntdRegistry>
            </StoreProvider>
          </AuthProvider>
        </StripeElement>
      </body>
    </html>
  );
}
