import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import NavbarPage from "../components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { ProvidersAntdRegistry } from "./AntdRegistry";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ProvidersAntdRegistry>
          <Providers>
            <NavbarPage></NavbarPage>
            {children}
            <Footer />
          </Providers>
        </ProvidersAntdRegistry>
      </body>
    </html>
  );
}
